### ISSUE TITLE
Reply content not shown on Android

### ISSUE THREAD

**Issue by taiko000** [pipacs/o2#116]
If you follow the Readme closely and open the browser in Android on 
void onOpenBrowser(const QUrl *url)
then the QTcpSocket in O2ReplyServer will pause processing network requests and the reply content will never be shown.
An easy fix is to change this line in the Qt-generated manifest.xml. 

meta-data android:name="android.app.background_running" android:value="true"

This should be documented in the Readme.

**Comment by pipacs** [comment]
The preferred way is to open a web view, not an external browser.
