### ISSUE TITLE
Facebook Example of O2Facebook doesn't run in qt 5.11 Desktop Release and Debug Builds But does Not Run

### ISSUE THREAD

**Issue by sykyck** [pipacs/o2#117]
Application Output - 
`Starting /root/Documents/QtProjects/o2/examples/build-facebookdemo-Desktop_Qt_5_11_1_GCC_64bit-Release/facebookdemo...
/root/Documents/QtProjects/o2/examples/build-facebookdemo-Desktop_Qt_5_11_1_GCC_64bit-Release/facebookdemo exited with code 1`
Apart from example not running why the linkingSucceeded() signal is emitted again in on linkingSucceeded slot

**Comment by pipacs** [comment]
Facebookdemo expects some command line parameters -- if none supplied, it exits with code 1.
