### ISSUE TITLE
Can I use this library with my non-Qt C++ application ?

### ISSUE THREAD

**Issue by ac800car** [pipacs/o2#126]
Hi Team,

I have written my Http application in C++ (non-Qt) . I want to add oauth2 functionality to it.
Could you please confirm if I can use this library with my non-Qt C++ application ?

Thanks in advance

**Comment by pipacs** [comment]
There is no UI in the library, but it uses (and depends on) the Qt libraries for basic data types, networking and more. So it won't be easy to interface with it.
