### ISSUE TITLE
Password grant?

### ISSUE THREAD

**Issue by richbourne** [pipacs/o2#33]
Hi,

Your lib is great.  Perfect for allowing my c++ app to get access to my Twitter or Facebook account without having a web server in the way. 

What I want to do is authenticate against my own oauth server using a simple password grant ( user, password, clientid only). Your lib handles adding tokens to subsequent outbound requests nicely but is geared towards an authorisation grant type, not a simple password grant against my own server. 

Would you consider a pull request that filled that gap?  Right now I have  php and .net oauth auth servers that I want my c++ apps to authorise against but your lib only does part of what I need, ie: it assumes url redirects etc, when I have no need for such mechanisms as I have my own simple oauth password grant server. 

If you'd be interested, I'd write one and submit a pull request. 

Thanks,
Rich

**Comment by pipacs** [comment]
Sure, patches are welcome. Just make sure your code is generic enough for a wider audience, follows the existing coding style, and makes new features accessible from QML as well. Thanks!
