### ISSUE TITLE
" Application is not linked to Twitter!" after link succeeded messege

### ISSUE THREAD

**Issue by boroskoyo** [pipacs/o2#35]
When I run the twitterdemo it starts the browser like it should and after I authorize the application I see the link succeeded message in the console but after that if I try to post a status it says application is not linked to twitter. I tried this with 2 different computers connected to different networks but still couldn't work it out. Could you help me to solve this problem?

note: I added 
LIBS += -LC:/OpenSSL-Win32 -llibssl32
LIBS += -LC:/OpenSSL-Win32 -llibeay32
LIBS += -LC:/OpenSSL-Win32 -lssleay32
to the .pro file to get rid of ssl problems.
I use qt 5.5 and msvc2012 32 bit on windows 10

**Comment by pipacs** [comment]
The Twitter demo is very old, Twitter authentication has been changed since it was written. Updates are most welcome.

**Comment by MartinBriza** [comment]
This problem is not caused by linking. There seems to be a problem storing the credential using QSettings. Its NativeFormat stores the data in the registry and it seems you can't have keys that contain the '.' symbol in them. Changing the key format or the QSettings driver in O2SettingsStore solves the problem.

**Comment by pipacs** [comment]
Thanks for investigating this! Would you submit the fix as a patch?

**Comment by MartinBriza** [comment]
I'll put something up before this weeks end I hope.

**Comment by boroskoyo** [comment]
It has been a while but I developed a twitter example with gui using your library, if you wish I can just share with you

**Comment by MomoPlay** [comment]
Could you share your code please boroskoyo ? I would really like to see a working example for twitter.

**Comment by pipacs** [comment]
Updated documentation about QSettings usage + added a complete working Twitter demo.
