### ISSUE TITLE
Twitter Demo don't work

### ISSUE THREAD

**Issue by MomoPlay** [pipacs/o2#69]
Hi, I tried the example you gave with the librairie, but they didn't work. Or at least I can not make it work.
The program run without error, but only the help is displayed,
Do you have any idea where the problem come from ?

**Comment by Swerved** [comment]
Yeah - Twitter have updated their authentication to o2 now iirc.

**Comment by pipacs** [comment]
Twitter is using OAuth 1.0a. The demo app _sialis_ works just fine.
