### ISSUE TITLE
Silent failure on windows

### ISSUE THREAD

**Issue by darakian** [pipacs/o2#75]
Hey all, just spent the day tracking down a bug when using o2 on windows. If
QCoreApplication::setOrganizationName();
QCoreApplication::setApplicationName();
Are not set then the Qsettings used in o2 will fail to write key value pairs (but will continue to run!). The return values end up being empty strings which causes everything to fail and when porting an application this can be quite annoying.

I'm mostly sharing so that others that hit this issue can find a quick fix, but it might be worth having o2 check if these are set and to set some defaults if not.

**Comment by ikushn-s** [comment]
I've also spent a day because of this bug. SmugMug authorization worked on Linux and Mac, but not on Windows. For me setting organization name alone suffices to fix the issue.
I think that the organization name should be set in the examples.

**Comment by pipacs** [comment]
Fixed by a77d5073074ecb4294a86f870cf971d465354161
