### ISSUE TITLE
Allow for multiple accounts (virtual token() and tokenSecret())

### ISSUE THREAD

**Issue by uppfinnarn** [pipacs/o2#8]
O2 currently takes liberties with the credential storage, which causes trouble for applications which can handle multiple accounts. Declaring O1::token(), O1::tokenSecret() and appropriate functions in O2 as virtual would allow subclasses to easily handle their own storage.

**Comment by pipacs** [comment]
Multi-account support can be implemented now by using different settings store instances with the per-account O2 instances.
