### ISSUE TITLE
No install documentation for noobs

### ISSUE THREAD

**Issue by X13X** [pipacs/o2#85]
Even I'm still trying to figure out how to use this with my project

Qt-5.9 - Windows. 8.1 Ming-Gw  - cmake installed

This in no way is entirely on pipac.  But people new to Qt like myself, have no idea how to implement this in our projects.

I have a qt-quick project which will import o2.  
I have opened a new quick project and (open project'd) cmake'd the 02 file system, the problem is how do I link o2 with keychain?  
Not only that, but how do I link o2 to my quick-project?

The documentation doesn't layout the steps, which is the exact reason noobs stay away from c++ and qt all together.

**Comment by pipacs** [comment]
We have a README documenting O2. About using Qt on Windows: that's out of this project's scope.
